MailService/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emailsender.urls', namespace='emailsender')),
]

emailsender/urls.py
from django.urls import path
from emailsender.views import EmailFormView, AwaitngMailsView

app_name = 'emailsender'

urlpatterns = [
    path('', EmailFormView.as_view(), name='send-mail'),
    path('mails-list', AwaitngMailsView.as_view(), name='mails-list'),
]

emailsender/models.py
from django.db import models


class Email(models.Model):
    text = models.CharField(max_length=150, verbose_name='Текст')
    email = models.EmailField(verbose_name='Почта')
    seconds = models.PositiveIntegerField(default=0, verbose_name='Секунды')

    def __str__(self):
        return self.email

emailsender/forms.py
from django import forms
from emailsender.models import Email


class SendEmailForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = '__all__'

emailsender/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from emailsender.forms import SendEmailForm
from emailsender.models import Email


class EmailFormView(CreateView):
    model = Email
    form_class = SendEmailForm
    template_name = 'send_emails.html'
    success_url = reverse_lazy('emailsender:send-mail')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return super(EmailFormView, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseRedirect('/admin')



class AwaitngMailsView(ListView):
    model = Email
    template_name = 'mails-list.html'
    context_object_name = 'mails'
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(AwaitngMailsView, self).get_context_data()
        context['sended'] = Email.objects.filter(seconds=0)
        context['awaitng'] = Email.objects.filter(seconds__gt=0)
        return context

emailsender/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Отправка писем</title>
</head>
<body>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}
<ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'emailsender:send-mail' %}">Отправить письмо</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'emailsender:mails-list' %}">Список писем</a>
  </li>
</ul>
{% block content %}


{% endblock content %}
</body>
</html>

emailsender/templates/mails-list.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm">
            <h2>Ожидают отправки</h2>
            {% for email in awaiting %}
            <p class='awaiting' >{{ email }}</p>
            {% endfor %}
        </div>
        <div class="col-sm">
            <h2>Отправленные</h2>
            {% for email in sended %}
            <p class='sended' >{{ email }}</p>
            {% endfor %}
        </div>
    </div>

</div>
<hr>
<nav aria-label="Pagination">
  <ul class="pagination justify-content-lg-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Назад</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Назад</a>
      </li>
      {% endif %}


      {% for n in page_obj.paginator.page_range %}
          {% if page_obj.number == n %}
              <li class="page-item active" aria-current="page">
                  <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
              </li>
          {%  elif n > page_obj.number|add:-3 and n < page_obj.number|add:3 %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ n }}">{{ n }}</a>
              </li>
          {% endif %}
      {% endfor %}


      {% if page_obj.has_next %}
      <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперед</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Вперед</a>
      </li>
      {% endif%}
  </ul>
</nav>

{% endblock content %}

{% block javascript %}
<script>

function update() {
  $.get('mails-list', function(data) {
    $('.body').html(data);
  });
}

setTimeout(update, 10000);

</script>

{% endblock javascript %}

emailsender/templates/send_emails.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<style>
  .form {
    margin-top: 2%;
  }
</style>
<div class="form">
  <form method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Отправить
    </button>
  {% endbuttons %}
</form>
</div>



{% endblock content %}